### ISSUE TITLE
margin between subitems / manual designator placement / Inherit label/description from first designator

### ISSUE THREAD

**Issue by cosmicdan** [FluffierThanThou/RW_ArchitectSense#8] opened 2017-06-29 03:50 UTC
Great idea, though the mod is unusable right now on A17 IMO.

Issues:
1. Spacing of submenu items is too small (see picture)
2. The recipe info pane (recipe/ingredients/description box above the main menu) always shows the first item (see picture - still shows campfire info when Nutrient Paste Dispenser is being hovered)
3. Not possible to make categories appear first with uncategorized items after (or is it? I tried order -9999 but that just put it in the middle)
4. Would be nice if the omission of label and/or description will instead inherit from the first item inside the menu (not a big deal but would be nice).

I could probably look at 1 (might be as simple as changing that hard-coded margin at https://github.com/FluffierThanThou/RW_ArchitectSense/blob/master/Source/ArchitectSense/FloatMenu_Subcategory.cs#L112) and maybe number 4 but 2 - the important one - is beyond me.

![clipboard01](https://user-images.githubusercontent.com/2092676/27670681-e3270e84-5cd1-11e7-96b4-78b07d8b3b35.png)

**Comment by FluffierThanThou** [comment] 2017-07-31 10:05
1; should be fixed in a recent PR, I'll have to look at that soon.
2; I believe this is identical to vanilla behaviour.
3; order is a zero-based index, you should be able to set it to 2 (so it comes after the cancel/deconstruct designators). Note that this is a bit fragile, setting an invalid index will result in errors, and I didn't spend too much time on detecting the number of special designators (e.g. those cancel/deconstruct ones). Come to think of it, I don't think I have ever even tested manual placement...
4; sounds like a good idea!

**Comment by FluffierThanThou** [comment] 2017-07-31 10:07
P.S. I appreciate the clear suggestions, but in future, could you make one issue per suggestion? It makes working with these a lot easier from an admin perspective.

**Comment by cosmicdan** [comment] 2017-07-31 10:28
Re: #2, that's a shame if it's not possible to implement. Maybe possible to hook a mouse hover event? I'm not sure it's how it is in vanilla, the popup menu for crops for example works well. Unless that's not the same kind of popup menu.

Yeah no problem regrading separate issues, you're absolutely right. Luckily 3/4 are resolved already heh.

On 31 Jul 2017, FluffierThanThou <notifications@github.com> wrote:
>1; should be fixed in a recent PR, I'll have to look at that soon.
>2; I believe this is identical to vanilla behaviour.
>3; order is a zero-based index, you should be able to set it to 2 (so
>it comes after the cancel/deconstruct designators). Note that this is a
>bit fragile, setting an invalid index will result in errors, and I
>didn't spend too much time on detecting the number of special
>designators (e.g. those cancel/deconstruct ones). Come to think of it,
>I don't think I have ever even tested manual placement...
>4; sounds like a good idea!

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by FluffierThanThou** [comment] 2017-08-10 21:31
1 has been implemented, 3 is a non-issue. 

I'll look at 2 and 4. 2 might be tricky.

**Comment by FluffierThanThou** [comment] 2017-08-10 21:35
Come to think of it, I don't like 4. The problem is that it's not really possible to know if label/description is intentionally blank, and I don't want to be making assumptions there. Fixing the label/description in xml or C# is trivial anyhow.

**Comment by FluffierThanThou** [comment] 2017-08-10 22:08
Note to self; 2 will require manipulating `RimWorld.ArchitectCategoryTab.DesignationTabOnGUI()`

**Closed as completed** 2018-08-14 18:54 UTC
Labels: enhancement, Maybe later
